new Rails API app called 'hello-rails-back-end pull request
theresetuyi/hello-rails-back-end pull request #1
Opened 2023-09-21 19:19 UTC by theresetuyi

## Create a new Rails API app called 'hello-rails-back-end'.

1. Initialize your project with Git.
2. Make sure that your project has a Postgres database set up.
3. Create a table for storing your messages and create 5 different greetings.
4. Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

2023-09-21 20:33 UTC, bienvenuushindi reviewed
Hi @theresetuyi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Thank you for your contribution. However, the README file for the frontend mentions that it should include a link to the backend part, which is currently missing in this Pull Request. In order to maintain consistency and completeness, please ensure that the link to the backend is added as per the project requirements. Until this requirement is fulfilled, I'm afraid we cannot proceed with  this Pull Request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-21 22:06 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @theresetuyi 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Set up a project with two app
- ✔️ Implement a connection between a Ruby on Rails back-end and React front-end

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 22:06 UTC, abdulhamiid commented on config/routes.rb
> +end
**Rails API**: 

I noticed that you do not have a route for the  `API` endpoint for returning a random greeting 👀 which is the reason for the error.

![image](https://github.com/theresetuyi/hello-rails-back-end/assets/78251927/c198e2a0-45a3-48dc-989b-24c03787425c)

For the API endpoint to display a random greeting, we will need to create a route in our `routes.rb` file. this asks the router to match it to a controller action.

example
```ruby
  get '/greetings' => 'greetings#index'
```

This will also allow the API URL in the React app to display a random greeting. 🤗🛠

2023-09-21 22:06 UTC, abdulhamiid commented on README.md
> +</details>
![image](https://github.com/theresetuyi/hello-rails-back-end/assets/78251927/3171bc82-1809-4ff9-a560-7c16a46af283)

For a professional repository, it is important that our links are working correctly.

Every link should navigate to the expected `URLs`. please correct this 💪😊

2023-09-22 00:48 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @theresetuyi 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Create API endpoint for returning random greeting 📌 
✔️ No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] The random greeting message doesn't get displayed on the front-end yet due to a CORS error as you can see below 👇 
![image](https://github.com/theresetuyi/hello-rails-back-end/assets/46839548/69ba6091-d4a2-4f27-8130-726d363f147b)
Cross-Origin Resource Sharing (CORS) errors typically occur when a web application hosted on one domain tries to request resources (e.g., API data) from another domain. In Rails, you can use the `rack-cors` gem to handle CORS configuration.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 19:11 UTC, mckent05 approved these changes
Hi @theresetuyi, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Good job setting up your rails and react project in one application 👏 👏 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 19:18 UTC, merged